module.exports = {
  'en-doc1': {
    id: 'en-doc1',
    title: 'Document 1',
    source: 'doc1.md',
    version: 'next',
    permalink: 'docs/en/next/doc1.html',
    localized_id: 'doc1',
    language: 'en',
    sidebar: 'docs',
    category: 'Test',
    next_id: 'doc2',
    next: 'en-doc2',
    next_title: 'Document 2',
  },
  'en-doc2': {
    id: 'en-doc2',
    title: 'Document 2',
    source: 'doc2.md',
    version: 'next',
    permalink: 'docs/en/next/doc2.html',
    localized_id: 'doc2',
    language: 'en',
    sidebar: 'docs',
    category: 'Test',
    previous_id: 'doc1',
    previous: 'en-doc1',
    previous_title: 'Document 1',
  },
  'ko-doc1': {
    id: 'ko-doc1',
    title: '문서 1',
    source: 'doc1.md',
    version: 'next',
    permalink: 'docs/ko/next/doc1.html',
    localized_id: 'doc1',
    language: 'ko',
    sidebar: 'docs',
    category: 'Test',
    next_id: 'doc2',
    next: 'ko-doc2',
    next_title: '문서 2',
  },
  'ko-doc2': {
    id: 'ko-doc2',
    title: '문서 2',
    source: 'doc2.md',
    version: 'next',
    permalink: 'docs/ko/next/doc2.html',
    localized_id: 'doc2',
    language: 'ko',
    sidebar: 'docs',
    category: 'Test',
    previous_id: 'doc1',
    previous: 'ko-doc1',
    previous_title: '문서 1',
  },
  'en-version-1.0.0-doc1': {
    id: 'en-version-1.0.0-doc1',
    original_id: 'doc1',
    title: 'Document 1',
    source: 'version-1.0.0/doc1.md',
    version: '1.0.0',
    permalink: 'docs/en/doc1.html',
    localized_id: 'version-1.0.0-doc1',
    language: 'en',
    sidebar: 'version-1.0.0-docs',
    category: 'Test',
    next_id: 'doc2',
    next: 'en-version-1.0.0-doc2',
    next_title: 'Document 2',
  },
  'en-version-1.0.0-doc2': {
    id: 'en-version-1.0.0-doc2',
    original_id: 'doc2',
    title: 'Document 2',
    source: 'version-1.0.0/doc2.md',
    version: '1.0.0',
    permalink: 'docs/en/doc2.html',
    localized_id: 'version-1.0.0-doc2',
    language: 'en',
    sidebar: 'version-1.0.0-docs',
    category: 'Test',
    previous_id: 'doc1',
    previous: 'en-version-1.0.0-doc1',
    previous_title: 'Document 1',
  },
  'ko-version-1.0.0-doc1': {
    id: 'ko-version-1.0.0-doc1',
    title: '문서 1',
    source: 'version-1.0.0/doc1.md',
    version: '1.0.0',
    permalink: 'docs/ko/doc1.html',
    localized_id: 'version-1.0.0-doc1',
    language: 'ko',
    sidebar: 'version-1.0.0-docs',
    category: 'Test',
    next_id: 'doc2',
    next: 'ko-version-1.0.0-doc2',
    next_title: '문서 2',
  },
  'ko-version-1.0.0-doc2': {
    id: 'ko-version-1.0.0-doc2',
    title: '문서 2',
    source: 'version-1.0.0/doc2.md',
    version: '1.0.0',
    permalink: 'docs/ko/doc2.html',
    localized_id: 'version-1.0.0-doc2',
    language: 'ko',
    sidebar: 'version-1.0.0-docs',
    category: 'Test',
    previous_id: 'doc1',
    previous: 'ko-version-1.0.0-doc1',
    previous_title: '문서 1',
  },
};
