version: 2
updates:
  # Update GitHub actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    labels:
      - 'pr: dependencies'

  # Update npm / Yarn dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    # Disable version updates for npm dependencies
    # https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
    open-pull-requests-limit: 0
    labels:
      - 'pr: dependencies'
    # Reduce supply chain risk, delay npm version updates,
    # but stay responsive to critical security updates
    # https://github.blog/changelog/2025-07-01-dependabot-supports-configuration-of-a-minimum-package-age/
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
