version: 2
updates:
  ########################
  # GITHUB ACTIONS UPDATES
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    labels:
      - 'pr: dependencies'

  ########################
  # NPM VERSION UPDATES
  - package-ecosystem: 'npm'
    directory: '/'
    exclude-paths:
      - 'examples/**'
    schedule:
      interval: 'weekly'
    # Do not spam too much, we'll adjust this setting if needed
    open-pull-requests-limit: 5
    labels:
      - 'pr: dependencies'
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
