/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mySiteSidebar: [{type: 'autogenerated', dirName: '.'}],

  // You can create as many sidebars as you want
  /*
  mySecondSidebar: [
    'doc1',  // doc id: filename or frontmatter id
    {
      type: 'category',
      label: 'Tutorial',
      items: ['doc2', 'doc3'],
    },
  ],
   */
};
