/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {Joi, URISchema} from '@docusaurus/utils-validation';
import type {
  SidebarItemConfig,
  SidebarCategoriesShorthand,
  SidebarItemBase,
  SidebarItemAutogenerated,
  SidebarItemDoc,
  SidebarItemLink,
  SidebarItemCategoryConfig,
  SidebarsConfig,
} from './types';

const sidebarItemBaseSchema = Joi.object<SidebarItemBase>({
  className: Joi.string(),
  customProps: Joi.object().unknown(),
});

const sidebarItemAutogeneratedSchema =
  sidebarItemBaseSchema.append<SidebarItemAutogenerated>({
    type: 'autogenerated',
    dirName: Joi.string()
      .required()
      .pattern(/^[^/](.*[^/])?$/)
      .message(
        '"dirName" must be a dir path relative to the docs folder root, and should not start or end with slash',
      ),
  });

const sidebarItemDocSchema = sidebarItemBaseSchema.append<SidebarItemDoc>({
  type: Joi.string().valid('doc', 'ref').required(),
  id: Joi.string().required(),
  label: Joi.string(),
});

const sidebarItemLinkSchema = sidebarItemBaseSchema.append<SidebarItemLink>({
  type: 'link',
  href: URISchema.required(),
  label: Joi.string().required(),
});

const sidebarItemCategorySchema =
  sidebarItemBaseSchema.append<SidebarItemCategoryConfig>({
    type: 'category',
    label: Joi.string().required(),
    // TODO: Joi doesn't allow mutual recursion. See https://github.com/sideway/joi/issues/2611
    items: Joi.array().required(), // .items(Joi.link('#sidebarItemSchema')),
    collapsed: Joi.boolean(),
    collapsible: Joi.boolean(),
  });

const sidebarCategoriesShorthandSchema =
  Joi.object<SidebarCategoriesShorthand>().pattern(
    Joi.string(),
    Joi.array(), // .items(Joi.link('#sidebarItemSchema')),
  );

const sidebarItemSchema = Joi.alternatives()
  .try(
    Joi.object().when('.type', {
      switch: [
        {is: 'link', then: sidebarItemLinkSchema},
        {
          is: Joi.string().valid('doc', 'ref').required(),
          then: sidebarItemDocSchema,
        },
        {is: 'autogenerated', then: sidebarItemAutogeneratedSchema},
        {is: 'category', then: sidebarItemCategorySchema},
        {
          is: 'subcategory',
          then: Joi.forbidden().messages({
            'any.unknown':
              'Docusaurus v2: "subcategory" has been renamed as "category".',
          }),
        },
        {
          is: Joi.string(),
          then: Joi.forbidden().messages({
            'any.unknown': 'Unknown sidebar item type "{.type}".',
          }),
        },
      ],
    }),
    sidebarCategoriesShorthandSchema,
    Joi.string(),
  )
  .id('sidebarItemSchema');

const sidebarSchema = Joi.alternatives().try(
  Joi.array().items(sidebarItemSchema),
  sidebarCategoriesShorthandSchema,
);

const sidebarsSchema = Joi.object().pattern(Joi.string(), sidebarSchema);

export function validateSidebarItem(
  item: Record<string, unknown>,
): asserts item is Exclude<
  SidebarItemConfig,
  string | SidebarCategoriesShorthand
> {
  Joi.assert(item, sidebarItemSchema);
}

export function validateSidebars(
  item: unknown,
): asserts item is SidebarsConfig {
  Joi.assert(item, sidebarsSchema);
}
