/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  someSidebar: [
    {type: 'doc', id: 'API/api-end'},
    {
      type: 'autogenerated',
      dirName: '3-API',
    },
  ],
};
