/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      href: '/showcase',
      label: 'Showcase',
    },
    {
      type: 'link',
      href: '/feedback',
      label: 'Feedback',
    },
  ],
};
