/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      href: '/changelog',
      label: 'Changelog',
    },
    {
      type: 'link',
      href: '/showcase',
      label: 'Showcase',
    },
    {
      type: 'link',
      href: '/feature-requests',
      label: 'Feature Requests',
    },
    {
      type: 'link',
      label: 'Chat with us on Discord',
      href: 'https://discord.gg/docusaurus',
    },
  ],
};
