name: Security

on:
  push:
    branches:
      - main
      - docusaurus-v**
  pull_request:
    branches:
      - main
      - docusaurus-v**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  supply-chain-checks:
    name: Supply Chain Checks
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          # No cache on purpose! We want SFW to fetch packages

      # See https://socket.dev/blog/introducing-socket-firewall
      - name: Install Socket Firewall Free
        run: npm install -g sfw

      # Ensure our monorepo has no vulnerable dependency
      - name: Install monorepo dependencies through SFW
        run: sfw yarn install --frozen-lockfile

      # Generate init template
      - name: Generate test-website project against main branch
        run: yarn create-docusaurus ../test-website classic --javascript --skip-install

      # Ensure our init template has no vulnerable dependency
      - name: Install test-website project through SFW
        run: sfw yarn install --frozen-lockfile || yarn install --frozen-lockfile || yarn install --frozen-lockfile
        working-directory: ../test-website
        env:
          npm_config_registry: http://localhost:4873

      # Ensure no unexpected lifecycle (preintall/postinstall scripts)
      - name: Forbid lifecycle scripts
        run: |
          yarn add @lavamoat/preinstall-always-fail --ignore-scripts

          cat > pnpm-workspace.yaml <<'YAML'
          strictDepBuilds: true
          allowBuilds: {}
          trustPolicy: no-downgrade
          blockExoticSubdeps: true
          YAML

          jq '.pnpm.strictDepBuilds = true' package.json > tmp && mv tmp package.json
          jq '.pnpm.onlyBuiltDependencies = []' package.json > tmp && mv tmp package.json

          pnpm install
