name: Tests

on:
  pull_request:
    branches:
      - main
      - docusaurus-v**
    paths:
      - package.json
      - yarn.lock
      - vitest.config.ts
      - test/**
      - packages/**
      - tsconfig.*.json
      - .github/workflows/tests.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['24.14', '26']
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn install --frozen-lockfile || yarn install --frozen-lockfile || yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Remove Theme Internal Re-export
        run: yarn workspace @docusaurus/theme-common removeThemeInternalReexport
      - name: Docusaurus Build
        # We build 2 locales to ensure a localized site doesn't leak memory
        # See https://github.com/facebook/docusaurus/pull/10599
        run: yarn build:website:fast --locale en --locale fr
        env:
          # Our website should build even with limited memory
          # See https://github.com/facebook/docusaurus/pull/10590
          NODE_OPTIONS: '--max-old-space-size=450'
          DOCUSAURUS_PERF_LOGGER: 'true'
      - name: Docusaurus site CSS order
        run: yarn workspace website test:css-order

      - name: TypeCheck website
        # see https://github.com/facebook/docusaurus/pull/10486
        run: yarn workspace website typecheck

      - name: TypeCheck website - min version - v6.0
        run: |
          yarn add typescript@6.0 --exact -D -W --ignore-scripts
          yarn workspace website typecheck

      - name: TypeCheck website - max version - Latest
        # For latest TS there are often lib check errors, so we disable it
        # Details: https://github.com/facebook/docusaurus/pull/10486
        run: |
          yarn add typescript@latest --exact -D -W --ignore-scripts
          yarn workspace website typecheck --project tsconfig.skipLibCheck.json
