name: Swizzle Tests

on:
  pull_request:
    branches:
      - main
      - docusaurus-v**
    paths:
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Swizzle
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: ['eject', 'wrap']
        variant: ['js', 'ts']
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Set up Node LTS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
          cache: pnpm
      - name: Installation
        run: pnpm install --frozen-lockfile || pnpm install --frozen-lockfile || pnpm install --frozen-lockfile

      # Swizzle all the theme components
      - name: Swizzle (${{matrix.action}} - ${{matrix.variant}})
        run: pnpm --filter website test:swizzle:${{matrix.action}}:${{matrix.variant}}
      # Build swizzled site
      - name: Build website
        run: pnpm build:website:fast
      # Ensure swizzled site still typechecks
      - name: TypeCheck website
        run: pnpm --filter website typecheck --project tsconfig.skipLibCheck.json
