name: Windows Tests

on:
  pull_request:
    branches:
      - main
      - docusaurus-v**
    paths:
      - package.json
      - yarn.lock
      - vitest.config.ts
      - test/**
      - packages/**
      - tsconfig.*.json
      - .github/workflows/tests-windows.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows-test:
    name: Windows Tests
    timeout-minutes: 30
    runs-on: windows-latest
    strategy:
      matrix:
        node: ['24.14', '26']
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn install --frozen-lockfile || yarn install --frozen-lockfile || yarn install --frozen-lockfile
      - name: Docusaurus Tests
        run: yarn test
      - name: Create a deep path
        # https://github.com/facebook/docusaurus/pull/4899
        # https://github.com/facebook/docusaurus/issues/5793
        run: |
          mkdir -p "website/_dogfooding/_pages tests/deep-file-path-test/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar"
          cd "$_"
          echo "# hello" > test-file.md
      # Lightweight version of tests-swizzle.yml workflow, but for Windows
      - name: Swizzle Wrap TS
        run: yarn workspace website test:swizzle:wrap:ts
      - name: Docusaurus Build
        run: yarn build:website:fast
        env:
          DOCUSAURUS_PERF_LOGGER: 'true'

      - name: TypeCheck website
        # see https://github.com/facebook/docusaurus/pull/10486
        run: yarn workspace website typecheck

      - name: TypeCheck website - min version - v6.0
        run: |
          yarn add typescript@6.0 --exact -D -W --ignore-scripts
          yarn workspace website typecheck

      - name: TypeCheck website - max version - Latest
        # For latest TS there are often lib check errors, so we disable it
        # Details: https://github.com/facebook/docusaurus/pull/10486
        run: |
          yarn add typescript@latest --exact -D -W --ignore-scripts
          yarn workspace website typecheck --project tsconfig.skipLibCheck.json
