name: V2 Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - name: Test
        run: yarn test
      - name: TypeCheck website
        run: yarn workspace website tsc
